In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [16]:
Xtrain = np.array([
    [1.0, 2.0, 3.0,],
    [1.2, 2.2, 3.1,],
    [1.9, 2.9, 3.9,],
    [1.8, 2.8, 3.8,],
    [1.1, 2.1, 3.1,],
])

Xtest = np.array([
    [1.55, 2.55, 3.55,],
])

In [17]:
scaler = StandardScaler()
Xtrain = scaler.fit_transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [18]:
Xtrain

array([[-1.06904497, -1.06904497, -0.98246661],
       [-0.53452248, -0.53452248, -0.72392277],
       [ 1.33630621,  1.33630621,  1.34442799],
       [ 1.06904497,  1.06904497,  1.08588415],
       [-0.80178373, -0.80178373, -0.72392277]])

In [19]:
Xtest

array([[0.40089186, 0.40089186, 0.43952454]])

In [15]:
Xtest = scaler.transform(Xtest)

In [9]:
Xtest

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
W1 = np.random.randn(shape=(4,5))

TypeError: randn() got an unexpected keyword argument 'shape'

In [24]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `numpy.random.standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argu

In [46]:
def he(v):
    # print(v)
    Wb = {}
    for i in range(len(v)-1):
        Wb['W'+str(i+1)] = np.random.randn(v[i], v[i+1]) * np.sqrt(1.0/v[i+1]) # He's weight initialization 
        Wb['b'+str(i+1)] = np.zeros(shape=(1, v[i+1]))
    #end-for
    return Wb

In [47]:
Wb = he([9, 8, 7, 6, 5, 4])

In [48]:
for i in range(1, 6):
    print(Wb['W'+str(i)].shape)
    print(Wb['b'+str(i)].shape)

(9, 8)
(1, 8)
(8, 7)
(1, 7)
(7, 6)
(1, 6)
(6, 5)
(1, 5)
(5, 4)
(1, 4)


In [49]:
W1 = Wb['W1']
W1

array([[ 0.19347784,  0.34041593,  0.08772882,  0.1827568 , -0.14792508,
        -0.22563147, -0.21370238, -0.08605773],
       [ 0.02254606, -0.11700125,  0.54284423, -0.42353979, -0.71920353,
        -0.20774765,  0.02814499,  0.2686192 ],
       [-0.2974761 ,  0.59853256,  0.07844121,  0.18805089, -0.37580162,
        -0.72618179,  0.08879101, -0.20212955],
       [-0.71096758,  0.14723629, -0.10922991,  0.02994116, -0.42607053,
        -0.19757654,  0.44732888, -0.10312401],
       [ 0.61193502, -0.00721698, -0.6058629 , -0.40516221,  0.17468086,
        -0.12182147,  0.2836643 ,  0.65535393],
       [-0.6499929 ,  0.14808717,  0.17005308, -0.01397257, -0.14696961,
         0.29882449, -0.15488859, -1.02161874],
       [ 0.44393338, -0.32888943,  0.19896456,  0.18268709, -0.13487625,
        -0.34292175,  0.56360665, -0.43245845],
       [-0.33018227,  0.23358325,  0.17601169,  0.78871924,  0.21160098,
        -0.13381972, -0.00157457,  0.11509689],
       [ 0.061039  , -0.58136911

In [51]:
np.square(5.0)

25.0

In [54]:
5.0**2.0

25.0

In [55]:
a = (1, 2, 3)

In [56]:
a

(1, 2, 3)

In [63]:
(x, y, z) = a

In [64]:
x

1

In [65]:
y

2

In [66]:
z

3

In [67]:
for i in range(5):
    print(i)

0
1
2
3
4


In [70]:
for i in reversed(range(5)):
    print(i)

4
3
2
1
0


In [69]:
list(reversed(range(5)))

[4, 3, 2, 1, 0]

In [71]:
a=np.array([
    [4, 5],
    [6, 7],
])

b=np.array([
    [4, 5],
    [6, 7],
])

In [72]:
np.dot(a, b)

array([[46, 55],
       [66, 79]])

In [73]:
np.multiply(a, b)

array([[16, 25],
       [36, 49]])

In [74]:
a*b

array([[16, 25],
       [36, 49]])

In [86]:
a

array([[4, 5],
       [6, 7]])

In [88]:
np.random.randn(*a.shape)

array([[ 0.60058302,  0.88033904],
       [-0.73207561,  0.6487433 ]])

In [83]:
type(*a.shape)

TypeError: type() takes 1 or 3 arguments

In [84]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `numpy.random.standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argu

In [89]:
a

array([[4, 5],
       [6, 7]])

In [90]:
b

array([[4, 5],
       [6, 7]])

In [91]:
a[1,1] = 17

In [92]:
a

array([[ 4,  5],
       [ 6, 17]])

In [93]:
b=a

In [94]:
b

array([[ 4,  5],
       [ 6, 17]])

In [95]:
b[1,0]=16

In [96]:
a

array([[ 4,  5],
       [16, 17]])

In [97]:
a

array([[ 4,  5],
       [16, 17]])

In [98]:
x = np.copy(a)

In [99]:
x

array([[ 4,  5],
       [16, 17]])

In [100]:
x[0,0] = 14

In [101]:
a

array([[ 4,  5],
       [16, 17]])

In [102]:
x

array([[14,  5],
       [16, 17]])

In [14]:
class Main:
    @staticmethod
    def work(self, a, b):
        for i in range(10):
            v = self.add(self, a, b)
            print(v)
    
    @staticmethod
    def add(self, a, b):
        return a+b

In [15]:
abc = Main()
abc.work(4, 5)

TypeError: work() missing 1 required positional argument: 'b'