In [1]:
import numpy as np
import tensorflow as tf

/home/mrz/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mrz/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mrz/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mrz/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: 

In [3]:
tf.__version__

'1.12.0'

In [2]:
def output(x):
    initi = tf.global_variables_initializer()
    
    with tf.Session() as session:
        session.run(initi)
        return session.run(x)

def outputPH(expression, placeholder, data):
    with tf.Session() as session:
        return session.run(expression, feed_dict={placeholder:data})

In [86]:
z = np.array([
    [1, 2, 3],
    [4, 5, 6.6],
])
z = tf.constant(z)

In [87]:
output(z)

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [88]:
a = tf.Variable(25.7, dtype=tf.float32, name='A')
b = tf.Variable(26.9, dtype=tf.float32, name='B')

In [89]:
output(a)

25.7

In [90]:
output(b)

26.9

#### Loss

In [91]:
Yp = tf.constant(36.0, name='Yp')
# Y  = tf.constant(39.6, name='Y')
# Yp = tf.Variable(36.0, name='Yp')
Y  = tf.Variable(39.0, name='Y')

loss = tf.Variable((Yp-Y)**2.0, name='loss')
output(loss)

9.0

In [92]:
a = tf.constant(36.0, name='a')
b = tf.constant(39.6, name='b')
c = tf.multiply(a,b)
c

<tf.Tensor 'Mul_14:0' shape=() dtype=float32>

In [93]:
output(c)

1425.6

In [94]:
session = tf.Session()
print(session.run(c))

1425.6


In [95]:
x = tf.placeholder(tf.float32, name = 'x')
# print(sess.run(2 * x, feed_dict = {x: 3}))

In [96]:
result = tf.multiply(x, x, name='y')
result

<tf.Tensor 'y_4:0' shape=<unknown> dtype=float32>

In [97]:
with tf.Session() as session:
    v = session.run(result, feed_dict={x:3})
    tf.summary.FileWriter('./logs/tg', session.graph)
    print(v)

9.0


In [100]:
outputPH(result, x, 3.5)

12.25

In [68]:
v = {'x':3}

In [69]:
v

{'x': 3}

In [70]:
v['x']

3

In [160]:
np.random.seed(101)

In [161]:
a = tf.constant(np.random.randn(3,2), name='a')

In [162]:
a

<tf.Tensor 'a_22:0' shape=(3, 2) dtype=float64>

In [163]:
output(a)

array([[ 2.70684984,  0.62813271],
       [ 0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804]])

In [179]:
# X = tf.constant(np.random.randn(3,1), name='A')
X = tf.constant(np.random.randn(3,1))
W = tf.constant(np.random.randn(4,3))
# Y = tf.multiply(W, X)

In [186]:
np.random.seed(1)
X = tf.constant(np.random.randn(3,1), name = "X")
W = tf.constant(np.random.randn(4,3), name = "W")
b = tf.constant(np.random.randn(4,1), name = "b")
Y = tf.matmul(W,X) * b

In [187]:
output(Y)

array([[ 1.16223591],
       [-0.5399318 ],
       [ 0.18558752],
       [-0.03746868]])

In [5]:
np.random.seed(101)
X = tf.Variable(np.random.randn(3, 1))
W = tf.Variable(np.random.randn(4, 3))
b = tf.Variable(np.random.randn(4, 1))
Y = tf.add(tf.matmul(W, X), b)

In [6]:
output(Y)

array([[ 2.43789462],
       [-3.55663117],
       [ 3.77952716],
       [ 1.79271391]])

In [7]:
help(tf.sigmoid)

Help on function sigmoid in module tensorflow.python.ops.math_ops:

sigmoid(x, name=None)
    Computes sigmoid of `x` element-wise.
    
    Specifically, `y = 1 / (1 + exp(-x))`.
    
    Args:
      x: A Tensor with type `float16`, `float32`, `float64`, `complex64`,
        or `complex128`.
      name: A name for the operation (optional).
    
    Returns:
      A Tensor with the same type as `x`.
    
    @compatibility(scipy)
    Equivalent to scipy.special.expit
    @end_compatibility



In [8]:
help(tf.nn.sigmoid_cross_entropy_with_logits)

Help on function sigmoid_cross_entropy_with_logits in module tensorflow.python.ops.nn_impl:

sigmoid_cross_entropy_with_logits(_sentinel=None, labels=None, logits=None, name=None)
    Computes sigmoid cross entropy given `logits`.
    
    Measures the probability error in discrete classification tasks in which each
    class is independent and not mutually exclusive.  For instance, one could
    perform multilabel classification where a picture can contain both an elephant
    and a dog at the same time.
    
    For brevity, let `x = logits`, `z = labels`.  The logistic loss is
    
          z * -log(sigmoid(x)) + (1 - z) * -log(1 - sigmoid(x))
        = z * -log(1 / (1 + exp(-x))) + (1 - z) * -log(exp(-x) / (1 + exp(-x)))
        = z * log(1 + exp(-x)) + (1 - z) * (-log(exp(-x)) + log(1 + exp(-x)))
        = z * log(1 + exp(-x)) + (1 - z) * (x + log(1 + exp(-x))
        = (1 - z) * x + log(1 + exp(-x))
        = x - x * z + log(1 + exp(-x))
    
    For x < 0, to avoid overflow in 

In [9]:
v = np.array([
    [4, 5, 6, 7],
    [8, 9, 10, 11],
])

In [14]:
v.reshape(1, -1).squeeze()

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
v

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
v.flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
v

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.random.randn(3,None)

TypeError: 'NoneType' object cannot be interpreted as an integer

In [18]:
tf.zeros_initializer()

In [19]:
b1 = tf.get_variable("b1", [25,1], initializer = tf.zeros_initializer())

In [20]:
b1

<tf.Variable 'b1:0' shape=(25, 1) dtype=float32_ref>

In [21]:
help(tf.get_variable)

Help on function get_variable in module tensorflow.python.ops.variable_scope:

get_variable(name, shape=None, dtype=None, initializer=None, regularizer=None, trainable=None, collections=None, caching_device=None, partitioner=None, validate_shape=True, use_resource=None, custom_getter=None, constraint=None, synchronization=<VariableSynchronization.AUTO: 0>, aggregation=<VariableAggregation.NONE: 0>)
    Gets an existing variable with these parameters or create a new one.
    
    This function prefixes the name with the current variable scope
    and performs reuse checks. See the
    [Variable Scope How To](https://tensorflow.org/guide/variables)
    for an extensive description of how reusing works. Here is a basic example:
    
    ```python
    def foo():
      with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
        v = tf.get_variable("v", [1])
      return v
    
    v1 = foo()  # Creates v.
    v2 = foo()  # Gets the same, existing v.
    assert v1 == v2
    ```
    
    If i